### ISSUE TITLE
Dropdown: Select menu text can run into chevron

### ISSUE THREAD

**Issue by humancompanion** [18F/web-design-standards#1039]
In many places the text in our dropdown menus is long enough that it runs into the chevron handle that indicates the field is a dropdown. This cause some usability issues in that the affordance for the dropdown is lost when the downward facing chevron is obscured.

For what it is worth, I fixed the problem in the USAJOBS design system by applying some padding-right to the select element:
https://github.com/USAJOBS/design-system/blob/gh-pages/_scss/element/_select.scss

**Comment by maya** [comment]
That is a good find @humancompanion and we ought to do the same. Thank you!

**Comment by elarenee** [comment]
picked up this issue!

**Comment by maya** [comment]
@elarenee feel free to familiarize yourself with: https://github.com/18F/web-design-standards/pull/1096 - there was an IE regression introduced on that solve that we couldn't figure out.

**Comment by arielkennan** [comment]
Hello! Wanted to share that NYC is running to this too on one of our projects and we'd love a fix. We also ran into the IE11 issue with the artifact. Thanks!

**Comment by juliaelman** [comment]
@arielkennan thank you for your comment and making us aware of this. I am going to add this to our upcoming sprint planning. We appreciate your patience and support!

**Comment by arielkennan** [comment]
Thanks for the quick reply! I'll also share our site once it launches you can see your beautiful work implemented on another .gov.

**Comment by arielkennan** [comment]
A breakthrough - this just in from one of our developers on how we were able to fix it: 

So in my original build I was using additional padding on the left (right for RTL) to make room for the decorative custom arrow so it wouldn't overlap the text. As you saw in IE11 this caused two sets of arrows. IE11's native arrow control was being pushed inside by the padding rather than sitting on top of it. 

Using

`select::-ms-expand {
  display: none;
}
`
I could selectively target IE11 and hide that native control. Then it was just a matter of fixing the background-size definition of the decorative custom arrow so it would work in IE11 and not appear like a tiny dot.

**Comment by maya** [comment]
That's great to hear you were able to fix this, @arielkennan! Linking @brendansudol's fix here which found the "tiny dot" issue so the team can implement the fix: https://github.com/18F/web-design-standards/pull/1097
