### ISSUE TITLE
[Lists]: ::before and ::after pseudo selectors should not be used for layout purposes

### ISSUE THREAD

**Issue by debracleaver** [18F/web-design-standards#1091]
Hey team,
My team is noticing that you're using pseudo selectors for layout purposes, namely to add margin to html elements.  This seems incorrect.  We'd love to know your reasoning for this, and/or for you to remove this wonky CSS and just add margin/padding to the element itself.  Here's an example from your CSS:

`ul li:after, ol li:after {
    content: "";
    display: block;
    margin-bottom: 0.5em;}`

That's ... bizarre.

**Comment by justinelam** [comment]
+1

**Comment by maya** [comment]
Hi there, thanks so much for the question. We get this a lot actually. The reason we do this is bc lists are actually difficult to align flush and this technique allows us to do so. 

We explain the reasoning here: https://github.com/18F/web-design-standards/issues/1027

Let us know if you have any questions!

**Comment by debracleaver** [comment]
i see our favorite issue is back open :)

**Comment by maya** [comment]
@debracleaver indeed! Closed it to soon, sorry, we typically wait around two weeks for a response from the issue opener before closing. Although we're discussing it internally as well. i.e. how important is standardizing alignment vs. working with the medium of the web.

**Comment by maya** [comment]
Adding in Luke Keller's feedback from the blog post (https://18f.gsa.gov/2016/04/05/three-teams-using-the-draft-us-web-design-standards-talk-about-their-experiences/):

>I'd like to see the Standards [...] remove the pseudo elements from list items by default. I've never seen this approach to list items before, so it would be nice if this treatment was handled through a class, i.e. usa-list-item.

**Comment by patrickcate** [comment]
I've run into this issue as well. After doing a fresh Drupal 7 install to look at the [Drupal 18f theme](https://github.com/18F/web-design-standards-drupal) project incorporating the standards, the list pseudo elements caused layout issues with the Drupal admin toolbar. 

I think this is going to cause major issues down the line as well because using the `ul` and `ol` tags for semantic html structures is very common. I foresee many sites trying to implement the WDS will have to regularly override these pseudo elements.

Perhaps a good middle ground would be to move the current pseudo element list styling to a utility class `usa-list`?

<img width="929" alt="screen shot 2016-04-21 at 9 58 15 pm" src="https://cloud.githubusercontent.com/assets/6277206/14740356/47f96b5c-085c-11e6-8fed-60ea17b77ef5.png">

**Comment by zaneriley** [comment]
@maya I know you're working with an entirely different scope, but we ran into a similar issues with this approach. I think this is the right way to go for lists, but putting it on the element itself might be too greedy.

Our solution was to un-style `ul` and `ol` completely, and then to put these styles on their own modifier class (e.g. `.--styled`):

```scss
ul, ol {
  // reset, unstyled lists out of the box

  &.primary {
    // standardize alignment styles
  }
}
```

This keeps from having to add extra code to undo the changes. The obvious caveat is that, it may be tough to work backwards to append class modifiers to elements in an existing codebase.

**Comment by maya** [comment]
@patrickcate @zaneriley thanks for those points, but I think it's different from the issue opened here which is about pseudo selectors. I've opened #1135 to address the specificity issue you bring up, feel free to add your thoughts there.
