### ISSUE TITLE
[Website] Errors on staging

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#1194]
## Issue type
What kind of issue are you working on?

* Website

## Description

Getting a lot of errors on staging in the console.

## Additional information [optional]

```
styleguide.js:1 Uncaught ReferenceError: $ is not defined
uswds.min.js:3 Uncaught Error: Did you forget to define selectors in the aria-controls attribute? Check element undefined
﻿```

**Comment by el-mapache** [comment]
@maya I know that the uswds.min.js error is caused by the start.js script running on pages where the DOM element being jQuery selected isn't available (i.e. targeting a form control on the accordion page). I added the error message when I put in the PR for JS testing.

Since start.js runs on every page, what do you think the best way to deal with an element that isn't there? We could add a conditional check in that script that only initializes plugins when the appropriate element exists.

**Comment by maya** [comment]
I thought I got more errors so opened a new issue but turns out I didn't. Closing in favor of: #1193.
