### ISSUE TITLE
[Labels]: Rename to something else.

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#1381]
## Description

While working with our own standards one of our developers put the Labels component for generating the HTML into a folder named "form controls". From a UX perspective this points to a misunderstanding of what the label element is from a user-perspective, versus what a label is from a developer perspective.

We have also run into times when designers have asked for tags and highlighted text and we point them to the Labels element: Is this the "wrong" place to point them?
## Proposal

Rename Label element to something else. Not sure what that might be.

**Comment by maya** [comment]
Hi @joshbruce, thanks for opening the issue. Agree that labels might be confusing for developers since `<label>` is an HTML element associated with form controls. We're not sure what else we could call them right now, but will let you know if we have any ideas. We found that "label" is a nice, abstracted way to refer to this component.

>We have also run into times when designers have asked for tags and highlighted text and we point them to the Labels element: Is this the "wrong" place to point them?

Although I'm not sure what "highlighted text" is, if your designer is looking for tags, then our labels are the right place! The label classes can be added to anchor links to make them into clickable tags.

**Comment by joshbruce** [comment]
Hi @maya. Thanks, as always. Re "highlighted text": A completely string of text - not a short bit. So, say I do a search, and we want to "highlight" part of the return value (obviously a different color background).

**Comment by donjo** [comment]
Closing this out for now since we're going to stick with the current name for Labels but we'll be sure to reference this post if other users seem to be encountering the same thing.
