### ISSUE TITLE
Make sure our documentation catalogues our compatibility with other frameworks [documentation]

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards#1388]
**Projected deadline: Within the next week or so**
## Description

Per the comms plan @jameshupp and I developed, we'd like to make sure our documentation correctly describes the Standards' compatibility with other frameworks (to prevent user frustration). 

Here's our tentative to-do list:
- [ ] Put a call out for review of current documentation
- [ ] Get copy recommendations from devs
- [ ] Update our documentation, as necessary
- [ ] Make any stylistic/copy edits
## Additional information [optional]

Not too much additional information — one thing to note is that we'll need a developer to help review our existing documentation for factual accuracy! (That explains the "Help Wanted" label.)

**Comment by donjo** [comment]
Closing this out for now since we've added a few things to enhance the dev experience around using our USWDS with other systems. There is the [customization and themeing](https://standards.usa.gov/getting-started/developers/#customization-and-theming) section and also the new `/examples` directory in the [main project](https://github.com/18F/web-design-standards/tree/develop/examples)
