### ISSUE TITLE
Working on standards: how to link standards to docs

### ISSUE THREAD

**Issue by bruffridge** [18F/web-design-standards#1501]
## Description

OK, after much ado, I've finally got a [dev environment setup](https://github.com/bruffridge/nasa-web-design-standards-docker) using Docker on my Mac to run my fork of the docs site (standards.nasa.gov) locally. I also have a fork of the standards within the same Docker container. I've followed [these instructions](https://github.com/bruffridge/web-design-standards-docs/tree/master#using-the-latest-version-of-the-uswds-package) to link docs to my local copy of the standards.

So now I need to know how to tweak the styles in the standards and have them appear in the docs site I'm running. Ideally I want to set it up so when I change a file in the `src` folder the jekyll site rebuilds itself and displays the change automatically. So for example if I make a change to a .scss file in `src` it should build the css and jekyll site gets rebuilt.

**Comment by kcjonesevans** [comment]
The directions on the linked repo you have seem to be different from the [web design standards docs](https://github.com/18F/web-design-standards-docs). Are you able to run the link and watch commands? 

I did not use docker to set up my dev environment on my mac, and only had issues with my glup install and xcode. Is this not an option for you?

**Comment by juliaelman** [comment]
@bruffridge thanks for opening this issue! @kcjonesevans is correct about running the `npm run watch` commands against both repos so that your assets compile when you make changes to either the Standards or website asset files. We are using [`watch`](https://www.npmjs.com/package/watch) and [`nswatch`](https://www.npmjs.com/package/nswatch) to make this happen.

You also have clearly pointed out where we need to update our documentation in the Standards - thank you! I'll be opening a new issue to make that update and help clarify this step in local dev.

**Comment by juliaelman** [comment]
@bruffridge I've open a new issue to make the `npm run watch` command more explicit in our docs. 

Also, it looks like your fork does not have the latest docs for the Standards repo and does not include that `watch` command documentation. 

Closing this issue, but please let us know if you run into any other issues!

**Comment by bruffridge** [comment]
Thanks @kcjonesevans and @juliaelman. Using staging instead of master branches of the two repos worked. Everything is working now on Docker. If you ever want to run the docs and standards on Docker [check out my Dockerfile and README](https://github.com/bruffridge/nasa-web-design-standards-docker).
