### ISSUE TITLE
Document Analytics Strategy Apporach

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1548]
## Description

Once the business objectives have been defined and the details for each created, the approach for getting those necessary trackers in place needs to be documented. This will included:

- Sources of data collection
- Frequency of reporting
- Method of communicating reports
- Necessary skills for implementation

**Comment by bradnunnally** [comment]
The write is being created - https://github.com/18F/web-design-standards/wiki/analytics-strategy

**Comment by acolter** [comment]
The Summary section states, "Our research has shown that potential users of the Draft USWDS want to see a mix of qualitative and quantitative metrics that show the value and usefulness of adopting the Draft USWDS."

*Why* do they want to see metrics? What problem will that solve or what will that allow them to do that they can't do now? Since that's left unsaid, it's difficult to determine whether *these* metrics will solve that problem.

**Comment by bradnunnally** [comment]
@acolter Here is the revised copy 

Our research has shown that potential users of the Draft USWDS want to see a mix of qualitative and quantitative metrics that show the value and usefulness of adopting the Draft USWDS. This need exists to help justify the use of USWDS to their peers, managers, and executive leadership. Government is naturally risk-averse, and seeing proof that the USWDS is being used successfully helps reduce the hesitation to adopting the USWDS. To meet this end, the team is going to focus on publishing metrics that showcase where the Draft USWDS have been put into use and to show quantitative measures that speak to the value and impact of the standards.

**Comment by bradnunnally** [comment]
Draft has been created. Iterations will be made next week to finalize.

**Comment by bradnunnally** [comment]
Refinement can be made during the next sprint.
