### ISSUE TITLE
Text width issues on documentation template

### ISSUE THREAD

**Issue by wslack** [18F/web-design-standards#1603]
## Description

Body text in https://standards.usa.gov/page-templates/docs/ is not wide enough and leads to a feeling of sparseness, especially in very wide monitors. Compare: https://federalist-docs.18f.gov/ and https://federalist.18f.gov/preview/18f/federalist-docs/uswds/ (screenshots below)

<img width="1419" alt="screen shot 2016-12-02 at 12 51 22 pm" src="https://cloud.githubusercontent.com/assets/10016577/20844503/1b5c77dc-b88e-11e6-9e15-84a58d2b3d51.png">
<img width="1418" alt="screen shot 2016-12-02 at 12 51 13 pm" src="https://cloud.githubusercontent.com/assets/10016577/20844502/1b5a69ce-b88e-11e6-9b02-f4fefae753a1.png">

Here's the template on a widescreen:
<img width="1272" alt="screen shot 2016-12-02 at 12 52 19 pm" src="https://cloud.githubusercontent.com/assets/10016577/20844521/31e80eee-b88e-11e6-9b51-8f9503971bf1.png">

The other tricky piece is that page headings are wider than the text, which looks bad. All of the text should be able to expand more for better information density and less white space.

**Comment by wslack** [comment]
https://federalist.18f.gov/preview/18f/federalist-docs/uswds/pages/how-federalist-works/ has an example where bulleted lists have different widths than other text. Does not look great. Any idea of timing for looking at this?

**Comment by juliaelman** [comment]
@wslack thanks for following up! @msecret was working on a solve for this [here](https://github.com/18F/web-design-standards/pull/1629). The sparseness is due to a `max-width` setting on that content. You can read more about that solve in the issue.

Also! We are doing our sprint planning session today to queue upcoming work for the weeks to come. This solve is definitely part of our first to-dos, but if you need something sooner please let me know and I'd be more than happy to help y'all out with a manual fix

**Comment by wslack** [comment]
Totally fine to wait for your process to run! I will hold on merging the USWDS code into federalist-docs and look forward to seeing the change.

**Comment by juliaelman** [comment]
I took a look and tried a few different approaches to accomplish this for the Standards overall. After doing so, I think it would be good to evaluate what it would take to customize the template on Federalist rather than make this change in the Standards main code base. In addition to my findings from this testing, our original design team had the following guidelines for why we made this width choice:

> Line length: Controlling the length of lines of text in extended copy makes reading more comfortable by helping readers’ eyes flow easily from one line to the next. Somewhere between 50 and 75 characters per line is broadly considered to be a readable line length, while 66 characters is considered the ideal. 

And while I agree that this `max-width` limitation does make the page look sparse, there is design rationale behind this choice.

@wslack I am going to close this issue for now and will reach out separately to see if we can come up with a direct solution for Federalist.

**Comment by wslack** [comment]
@juliaelman only question is that right now, it seems like the line length control is inconsistent between standard text and lists or bullets: https://federalist.18f.gov/preview/18f/federalist-docs/uswds/pages/using-federalist/launch-checklist/

I understand if there's a design choice to limit characters but the different lengths make pages look choppy.

**Comment by wslack** [comment]
This issue is now tracked here: https://github.com/18F/federalist-docs/issues/45
