### ISSUE TITLE
Draft Content Editorial Process

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1708]
Define the process which the team will follow when making quick updates to the https://github.com/18F/web-design-standards-docs repo. The goal here is to create a process which allows us to quickly add, modify, or remove content and to quickly fix any broken links that can be done in a timely manner without breaking anything.

**Comment by bradnunnally** [comment]
General outline and high level flow I wrote yesterday. Sorry for taking so long to post here for review. 

Wds Website Editorial Workflow

Any member of the team should be empowered to make small updates to the content of the main website without having to wait for a new release to be created. The changes that should still go through the normal release process deal with major content changes to the site, structural changes to the site itself, and new content that is being added to the site. 

1 - Flag content that needs to be updated as an issue on github
2 - Create branch to create the change
3 - Make the content update and flag another team member for review. 
4 - Once content change has been approved, create a pull request that merges the created branch with Master. 

Thoughts @juliaelman @shawnbot @yowill

**Comment by bradnunnally** [comment]
I've placed this guidance on the docs repo wiki - https://github.com/18F/web-design-standards-docs/wiki/Content-Editing-Workflow

It's ready for review.

**Comment by juliaelman** [comment]
@bradnunnally looks good. I think there will be times where we merge directly into `master`, but that will be few and far between. It might be good to utilize [the labels we have in place](https://github.com/18F/web-design-standards/wiki/Label-glossary#priority) for categorizing the priority of a fix.

For example, if something is needing to be resolved ASAP we label it `Critical` and are aware that it would then be merged directly to `master`.

Also, it might make sense for us to add this to the [`CONTRIBUTING.md`](https://github.com/18F/web-design-standards-docs/blob/staging/CONTRIBUTING.md) instead of a wiki page so that contributors are aware of this workflow process.

**Comment by bradnunnally** [comment]
@juliaelman Can you take another look today? If the updates look good, I'll incorporate them into the contributing.md file for cross reference.

**Comment by juliaelman** [comment]
We've had some internal discussion around this editorial workflow and what the use case is. I am a bit confused as to why we need a specific use case that is different from our normal git workflow? What is the problem statement here?

**Comment by bradnunnally** [comment]
@yowill Can you provide some guidance? I recall this issue came about from a problem that you saw or foresaw happening.

**Comment by bradnunnally** [comment]
Closing this issue as our existing process already accounts for this.
