### ISSUE TITLE
Accordions don't work via mouse on devices that support both touch and mouse

### ISSUE THREAD

**Issue by paultag** [18F/web-design-standards#1993]
https://standards.usa.gov/components/form-templates/

The code accordions aren't expanding anymore - I know there were some new releases, this seems to have broken since

**Comment by wslack** [comment]
Hmmm. I had the same issue but it was fixed in https://github.com/18F/web-design-standards-docs/pull/279 and the accordions are working just fine for me now. Have you tried clearing cache?

**Comment by donjo** [comment]
@paultag they seem to be working for me too. I'd try clearing the cache as suggested but if that doesn't work, let us know what browser + operating system you're using and check to make sure your browser isn't blocking javascript resources.

**Comment by paultag** [comment]
Still broken after uninstalling and re-installing both Chrome and Firefox. I'm using GNU/Linux, but that shouldn't matter - I'm using Chrome Version 59.0.3071.115 (Official Build) (64-bit).

I'm fine closing this if it's just me

**Comment by wslack** [comment]
So weird though! You see this in the code right? <button class="usa-accordion-button" aria-controls="code-text-input" aria-expanded="true">Code</button>

**Comment by toolness** [comment]
I'm curious if this might be related to #1999, which involves accordions and/or menus not working and is specific to Windows 7/8.  Browser bugs specific to operating systems are unusual but sometimes happen, especially with new-ish platform features, e.g. `position: sticky` at https://github.com/18F/calc/pull/1455#issuecomment-283992122. I'm not familiar enough with our accordion code to have any hunches, though.

**Comment by mjoyce91** [comment]
This is also not working for me on Windows 10 with Chrome 59.0.3071.115 and Opera 46.0.2597.32. Works in Microsoft Edge. Also, the mobile responsive header/menu button does open as well.

**Comment by toolness** [comment]
Thanks especially to the efforts of James Frankowski, I think we've zeroed-in on at least one cause of this problem: our event-handling code is "Apple-centric" in that it's making the assumption that a device is *either* touch-based *or* has a mouse, but can't be both.  In [`src/js/events.js`](https://github.com/18F/web-design-standards/blob/5cf8e96504036d479fcc5c71e1ac0b11d22b1662/src/js/events.js):

```js
module.exports = {
  CLICK: ('ontouchstart' in document.documentElement)
    ? 'touchstart'
    : 'click',
};
```

This `CLICK` symbol is used in several places throughout the code to attach event handlers, and it's essentially saying, "if the user's device supports touch, respond to `ontouchstart` events, otherwise respond to `click` events".  This is fine for Apple devices which only support one or the other, but it means that on non-Apple devices which support *both*, such as the Microsoft Surface Pro, users will *only* be able to interact with some USWDS components using their touchscreens.

@mjoyce91 and @paultag -- do either of your systems have touchscreens?  If so, does tapping on the accordions work?  If not, could you [open up your JS console](https://developers.google.com/web/tools/chrome-devtools/console/#open_as_panel) and type the following:

```
'ontouchstart' in document.documentElement
```

If the console prints out `true`, then this is definitely our culprit!

Again, huge thanks to James Frankowski for doing much of the detective work on this.

**Comment by paultag** [comment]
Can confirm - I have a touch screen, touching the bar works, clicking does not

:us:

**Comment by mjoyce91** [comment]
I won't have access to the the computer I experienced this with until later today, but it does have a touch screen.

**Comment by wslack** [comment]
What a bug. Good job @toolness.
