### ISSUE TITLE
H3 tag in address element not valid according to spec

### ISSUE THREAD

**Issue by bruffridge** [18F/web-design-standards#2088]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address

https://github.com/18F/web-design-standards/blob/develop/src/components/10-footer/footer.njk#L49

**Comment by AndreaSigz** [comment]
Thanks @bruffridge. @donjo @toolness

**Comment by toolness** [comment]
Good catch, @bruffridge!

To clarify, the problem is with this HTML in our footer template:

```html
        <address>
          <h3 class="usa-footer-contact-heading">Agency Contact Center</h3>
          <p>(800) CALL-GOVT</p>
          <a href="mailto:info@agency.gov">info@agency.gov</a>
        </address>
```

The problem is that according to the [HTML5 `<address>` specification](https://www.w3.org/TR/html5/sections.html#the-address-element), `<address>` elements can't contain headings. 

I wonder if we should lift the `<h3>` outside of the `<address>` element, so that it's the previous sibling of the `<address>`?

**Comment by msecret** [comment]
@toolness I think lifting the `<h3>` out is a good solution.
