### ISSUE TITLE
disable form submission on components site

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards#2101]
request from GSA IT. See slack:

https://gsa-tts.slack.com/archives/C050HRGN7/p1502394104797479

**Comment by wslack** [comment]
ty ty @donjo 

Here's the previous PR (I think) that did this.

**Comment by toolness** [comment]
Er, so to clarify, by "components site" we specifically mean https://components.standards.usa.gov/, right?  The docs site at https://standards.usa.gov/ is fine and doesn't need to be touched?  Just wanted to make sure because I originally misinterpreted this issue to mean "the UI components section of the docs site", which is why I filed #378.

I'll start a totally different PR tomorrow morning to address this issue on components.standards.usa.gov!

**Comment by wslack** [comment]
Correct @toolness! I mean "components" like components.standards.usa.gov - if we should change that URL to be clearer, that is ok with me.
