### ISSUE TITLE
Having a max-width on forms can be problematic

### ISSUE THREAD

**Issue by msecret** [18F/web-design-standards#327]
The rule that sets a max width on all forms is problematic, partially because the maxwidth being set is pretty small. 

https://github.com/18F/usfwds/blob/63570a9810deb72ab7dd7773497970315d3ea1c9/assets/_scss/components/_forms.scss#L5

I'd prefer to not have my form messed with.

**Comment by maya** [comment]
We're following visual design guidelines so cc'ing @mollieru and @angel if they be interested in changing it.

**Comment by webinista** [comment]
Just ran into this. This media query:

    @media screen and (min-width: 600px) {
        form {
           max-width: 32em;
        }
    }

Results in a very narrow form width at larger viewports.
![screen shot 2016-01-28 at 11 35 03 am](https://cloud.githubusercontent.com/assets/354277/12651094/317dbd9c-c5b3-11e5-861d-b714995e05ae.png)

The `min-width` part of the query should probably be `max-width` instead.

**Comment by maya** [comment]
@webinista thanks for bringing this up! That is actually the intended width of the form. To get the wider width, you can add `usa-form-large` class to your form element. This has a `max-width: 46rem` and will give you a wider width like the mailing address form: https://playbook.cio.gov/designstandards/form-templates/#address-form

<img width="819" alt="screen shot 2016-01-28 at 8 44 33 am" src="https://cloud.githubusercontent.com/assets/5249443/12651450/6c4a7f54-c59b-11e5-97f4-4a3416642d47.png">


The `min-width` part of the query was intended as we use mobile-first media queries.

**Comment by shanear** [comment]
@maya The width of the form fields is great, but by putting the `max-width` property on `form` we're having a difficult time positioning things that may not fall into that max width, like our submit buttons.

see the screenshot below to see what we're talking about:

![screenshot 2016-02-12 11 21 14](https://cloud.githubusercontent.com/assets/1596259/13012885/2c57f642-d17b-11e5-8129-1275d67eded4.png)

Right now our only option seems to be to override the `max-width` property on form.

Could you tie the style to a class like `.usa-form` instead of the `form` element itself?
So we could do something like this:
```
<form>
  <div class="usa-form">
    <input type="text"/>
  </div>
  <input type="submit"/>
<form>
```

**Comment by carodew** [comment]
Hi @shanear – I've recently heard this feedback from someone else as well. We'll be doing a deeper dive into our form-related components in the relatively near future. Would you be willing to participate in a user interview so we can find out more about your experience working with the standards?

**Comment by shanear** [comment]
@carodew definitely :+1:
