### ISSUE TITLE
[Need input] max-width line length guidance: 75 char max, 2/3 grid width...or something else?

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#406]
Calling on design minds to give us some feedback. We've been tussling with the conundrum of how to provide guidance on line length for text.  

Originally, we'd suggested using the best-practice 75 characters (or 53rem) max-width (lots on this here: http://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/).  However, when we implemented this on our site, we all agreed the text blocks felt very narrow. Here is the result, in two contexts:

![screen shot 2015-09-02 at 10 45 01 am](https://cloud.githubusercontent.com/assets/3680494/9634824/6a64a0a6-5161-11e5-977a-27af99e5a6fb.png)

![screen shot 2015-09-02 at 10 46 15 am](https://cloud.githubusercontent.com/assets/3680494/9634815/63180d38-5161-11e5-8d4a-9a453066d7f3.png)

We are considering expanding to 2/3 of our grid (or 65rem).  Here is the result in the same two contexts:

![screen shot 2015-09-02 at 10 45 30 am](https://cloud.githubusercontent.com/assets/3680494/9634826/6f61dca4-5161-11e5-82a0-a13afbffbc7f.png)

![screen shot 2015-09-02 at 10 46 36 am](https://cloud.githubusercontent.com/assets/3680494/9634805/5d244888-5161-11e5-9b57-5699a5825230.png)

Would love to quickly see how this guidance would play out in a few of the products you guys are working on @jenniferthibault @jjoteal @ericronne @kharshawat @emilyville @mebates @dannychapman -- and any other thoughts you have on the matter.  We're hoping to make a call on this today (Weds, Sept 2). 

cc @angel @carodew @colinpmacarthur

**Comment by maya** [comment]
I would choose a max-width for paragraph text but not sure if it makes sense to use for alerts. Typically alerts go full-width.

**Comment by mollieru** [comment]
Well, the readability needs remain true, even in alerts. If there is more than one sentence for alerts, it seems we shouldn't be putting text at full width.  

In any case, more interested in the general guidance -- not just the specific alerts use-case.

**Comment by dannychapman** [comment]
A good compromise for alerts might be to center them with 2/3 grid width line length. Just a thought.

**Comment by jjoteal** [comment]
I frequently refer to this tool: http://www.pearsonified.com/typography/ when trying to figure out the optimal character count per line per the golden ratio. This might be a good place to start, as it will suggest the optimum readability recommendation for the specs that you enter.

**Comment by jenniferthibault** [comment]
*Holds breath for opinion that is probably in the minority....* but....

I actually don't find the first executions (with 75 characters/53rem max-width) to be too narrow **relative to the size of the characters**! I even find the second options with longer lines to be too long **relative to the size of the characters**. I wonder: are you viewing this on a thunderbolt monitor? Or a laptop with a larger than 15-inch screen? That could account for the extra white space that feels imbalanced to us big screened designer-types. Just a thought.

I make the distinction about size of character above, because that's what influences readability. Visually, yes, I do find that in your screen shots of the 75 ch mockup above you have some extra white space that is making the layout feel sparse (which I think, you are trying to solve by taking up some of that space with wider body copy lines). But the readability of the line lengths I find to be excellent! While reading the lines, my eye did not drift, or ache for a break to help me keep my place, as they did in the second set of layouts.

I am also with @mollieru on the alert lengths: would not make them full width, but would keep to the character-bound ratio for readability, no matter if they are one sentence or one paragraph. Same source as @jjoteal for tinkering with the conversions, but check out this article on the same site for a skimmable long read on typography ratios on the web if you want a little more: http://www.pearsonified.com/2011/12/golden-ratio-typography.php

**Comment by carodew** [comment]
I wasn't going to weigh in but here is my two cents – 

We've got a bit of a challenge here in that we don't know how users are going to implement text in their sites. If we did, I think we could say something like "don't have text span more than # columns" and then we design our grid takes care of the line length. Or we suggest a # of columns for main content area. 

Are we trying to control something we can't control by adding a max-width style on `<p>` text? How much is this something we should enforce via CSS rules in the pattern library vs. recommending best practices and trusting designers to make the best choice? And/or is this a v2 release when we can get into recommended page layouts more in depth? 

For the design standards site itself, I prefer the first set on the paragraph text, v2 could simply be adding a column of white space at wide screens across the right margin.I'm not a fan of either alert options.  I think the alert box should be about as wide as the text within it. `</nothelping></sorry>`

**Comment by mollieru** [comment]
Ok thank you guys all for your input! 

Based on the feedback from you all, we will offer specific line-length guidance for the recommended web design standards typography, followed by general guidance for setting line length if you customize to your own fonts.

**Comment by msecret** [comment]
I wanted to add my opinions here for future reference. I don't think any of this needs attention before MVP, but wanted my opinion to be written down for the future of the library.

From a front end developer perspective, I agree with Caroline in that we shouldn't force a max width with CSS but should offer guidance on how to treat text. Here is my reasoning:
- Enforcing a max width on all p tags is very strict from a code standpoint. People use and write HTML in many different ways and I don't think we can see all the cases where people wouldn't want a max width on their p tags. For instance, even our library has a "lead-text" class that we apply to p tags to make them larger in font size. Our max-width seems misplaced here because larger text doesn't need as small of a max-width.
- The majority of websites and CSS frameworks/libraries don't have this convention of forcing a max width. We should have a really good reason for choosing to build something that doesn't go along with the majority. I'm confused as why we didn't even consider or discuss other libraries and frameworks in our decision.
- It misses a good opportunity to stand apart from CFPBs library and be more broad and all encompassing.
- It requires confusing logic in CSS for lists vs paragraphs. We have rules to set a max width on all `<p>` tags but we can't enforce this on lists, `<ul>`'s, because theres way too many use cases where they shouldn't have a max width. This means all `<ul>`'s require a class to be set on them to set their max width while `<p>`'s will have it already set because the class is set at a more global level. This is bad programming because the user has to remember to do different things in different contexts to get the same result.

I also wanted to discuss a few opinions with the current implementation of max-width. Essentially, if we're going with a forced max width, I think we should follow CFPB a little more closely. It looks like they have a well thought-out implementation of max width.
- Our max width doesn't align with any of our grid classes. On CFPBs site, their max-width is the same width as their 2/3 grid class. This means a developer can easily mix and match p tags with grid-based content. Instead, our max-width is smaller then our 2/3 grid class. I think this could lead to problems for developers who want to line content up. I think we should ensure our max-width lines up with our grid as it will lead to a much cleaner interface for design and developers. I've attempted to show this in the following screenshot:
![screen shot 2015-09-08 at 10 54 34 am](https://cloud.githubusercontent.com/assets/1701077/9743436/3e392f6a-561b-11e5-8813-b8cbe3e4484b.png)

- I think if we force max-width we should embrace it more fully, meaning we shouldn't have our container classes (like accordions and alerts) have text that doesn't fill their space. This means these classes should have the same width as our max width to ensure there is empty space in them like there is now. This is done on CFPBs library through the use of grids(https://cfpb.github.io/design-manual/ui-toolkit/expandables.html), which we should emulate.
- I think we should apply a max width to paragraphs with a class rather then a blanket rule as we are doing now or at least at a more specific level the the whole document. This will keep in consistent with the `<ul>` tags as I was talking about above. It would also negate many of the points I brought above about being too strict from a code standpoint. While it will be more markup and I'm still not 100% onboard with this implementation, it's a more consistent code interface and less strict of a rule allowing more freedom for the developer.

**Comment by maya** [comment]
@msecret we could also recommend using the 2/3 grid for main content and an optional sidebar as the "default" layout. Since there is a mismatch between 2/3's layout and max width text, we could make our main container smaller and/or make our desktop text larger, until they match. This would offer the most flexibility and interchangeability between the two approaches.

Currently we are using max-width of text within `usa-content` class, so its up to devs to decide how close they should add the class to their content. Some devs may choose to add it site wide. Others may add it per text block.

**Comment by carodew** [comment]
This sounds like a good conversation to reference in a card in the Trello
Ice Box, so we don't lose these ideas when we look at post-MVP planning.

On Tue, Sep 8, 2015 at 4:52 PM, Maya Benari <notifications@github.com>
wrote:

> @msecret <https://github.com/msecret> we could also recommend using the
> 2/3 grid for main content and an optional sidebar as the "default" layout.
> Since there is a mismatch between 2/3's layout and max width text, we could
> make our main container smaller and/or make our desktop text larger, until
> they match. This would offer the most flexibility and interchangeability
> between the two approaches.
>
> Currently we are using max-width of text within usa-content class, so its
> up to devs to decide how close they should add the class to their content.
> Some devs may choose to add it site wide. Others may add it per text block.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/usfwds/issues/406#issuecomment-138696621>.
>



-- 
Carolyn Dew
carolyn.dew@gsa.gov
470 558 4323
@18F

**Comment by jpyuda** [comment]
I tend to think @msecret is right in terms of implementation details (though I tend to agree we would incur too much risk to change this right now).

In general, the max-width as implemented here is probably over-simplified. The 45-to-75 character rule of thumb (for single-column text, 66 is often recommended) is:
* a _rule of thumb_, not necessarily something to be followed in a hard-and-fast way
* meant to refer to long-form copy. Shorter pieces of text (like the alerts mentioned above, footnotes, pullquotes, headers, etc.) can often have longer line lengths comfortably.
* only one dimension: legibility is affected by line length, leading (line height), typeface, weight, and other factors

Also of note, the average characters per line will vary by typeface and, in some cases, type size (depending on the type design). It will definitely vary based on roman/italic/bold.

I'm thinking about how to boil down a topic as complicated as typography (there are entire books written on the topic, after all) into guidance that can be generally applicable. But it's probably right to offer guidance, not limits in this case.

**Comment by jpyuda** [comment]
A couple of other notes:
* the method I prefer to calculate line lengths (which involves measuring the length of a lowercase alphabet and doing some conversions) puts 53rem at closer to the 66-character "sweet spot" than the 75-character max. So there's room to go a little wider (the 2/3 grid seems like it might be okay, though I'm not sure how many ems that is right now)
* sizing in rems might be easier from a development standpoint than sizing in ems, but if we're talking about using different font sizes in some applications (alerts and footnotes would be great examples of this), then a max-width based on rems would be actively harmful. ems would be better.

**Comment by carodew** [comment]
Seems like this has been resolved by #665. Can this issue be closed? @mollieru @maya @colinpmacarthur @jpyuda (I don't know who to ping, clearly).

**Comment by mollieru** [comment]
Yep, closing now!
