### ISSUE TITLE
Update font pairings

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#409]
The font pairings guidance needs to be updated to depict what's actually used.

<img width="670" alt="screen_shot_2015-09-01_at_9_37_25_am" src="https://cloud.githubusercontent.com/assets/5249443/9645452/8ffd56fe-5180-11e5-8a10-36752a5573a0.png">

**Comment by angel** [comment]
Ok, here are the changes:

### Pairing 1: Default: Merriweather headers, Source Sans Pro body (basic)
**Display** line-height: 1.3em/68px
**h1** line-height: 1.3em/52px
**h2** line-height: 1.3em/39px
**h3**  line-height: 1.3em/26px
**h4**  line-height: 1.3em/22
**h5** line-height: 1.3em/20px
**h6** font-family: 'Source Sans Pro'; font-weight: 400; line-height: 1.3em/17px
**Lead paragraph**  font-size: 20px (not reflected in example); also should be Merriweather in the example; line-height: 1.7em/34px
**Body copy**  line-height: 1.5em/26px 
**Italic body copy**  line-height: 1.5em/26px

### Pairing 2: Merriweather headers, Source Sans Pro body (robust)
**Display 1** line-height 1.3em/68px
**Display 2** font-weight: 300, line-height: 1.3/52px
**h1** line-height: 1.3em/52px
**h2** line-height: 1.3em/39px
**h3**  line-height: 1.3em/26px
**h4**  line-height: 1.3em/22
**h5** line-height: 1.3em/20px
**h6** font-family: 'Source Sans Pro'; font-weight: 400; line-height: 1.3em/17px
**Lead paragraph 1**  line-height: 1.7em/34px; font-weight 300 (not reflected in example)
**Lead paragraph 2** font-size: 17px; font-weight: 300 (not reflected in example); line-height: 1.7em/29px
**Body copy** line-height: 1.5em/26px; ssp not reflected in example
**Italic body copy**  line-height: 1.5em/26px; ssp not reflected in example 

### Pairing 3:Merriweather with minor Source Sans Pro
**Display 1**  line-height 1.3em/68px
**Display 2** font-weight: 300; line-height: 1.3/52px
**h1** line-height: 1.3em/52px
**h2** line-height: 1.3em/39px
**h3**  line-height: 1.3em/26px
**h4**  line-height: 1.3em/22
**h5** line-height: 1.3em/20px
**h6** font-family: 'Source Sans Pro'; font-weight: 400; line-height: 1.3em/17px    
**Lead paragraph 1**  line-height: 1.7em/34px; font-weight 300 (not reflected in the example)
**Lead paragraph 2** font-weight: 300 (change in example); font-size: 17px; line-height: 1.7em/29px
**Body copy** font-family: 'Merriweather'; font-size: 15px; line-height: 1.7em/26px
**italic body copy** font-family: 'Merriweather'; font-size: 15px; line-height: 1.7em/26px

### Pairing 4: Source Sans Pro only
1. should say 300 not 700
**Display 1** line-height: 1.3em/77px
**Display 2** font-weight: 300; line-height: 1.3em/57px
**h1** line-height: 1.3em/57px
**h2** line-height: 1.3em/44px
**h3** line-height: 1.3em/31px
**h4** line-height: 1.3em/25px
**h5** line-height: 1.3em/21px
**h6** font-weight: 400; line-height: 1.3em/17px
**Lead paragraph** line-height: 1.5em/33px; example should be 300 weight
**Body copy** line-height: 1.5em/26px
**Italic body copy** line-height: 1.5em/26px

### Pairing 5: Source Sans Pro headings, Merriweather body
**Display 1** line-height: 1.3em/77px
**Display 2** font-weight: 300, line-height: 1.3em/57px
**h1** line-height: 1.3em/57px
**h2** line-height: 1.3em/44px
**h3** line-height: 1.3em/31px
**h4** line-height: 1.3em/25px
**h5** line-height: 1.3em/21px
**h6** font-weight: 400, line-height: 1.3em/17px
**Lead paragraph** font-family: 'Merriweather'; font-size 20px (not reflected in example); line-height: 1.7em/34px; also example should be 300 weight
**Body copy**font-family: 'Merriweather'; font-size: 15px; line-height: 1.7em/26px
**Italic body copy** font-family: 'Merriweather'; font-size: 15px; line-height: 1.7em/26px

Also, Pairings that only have one lead paragraph should just say lead paragraph instead of lead paragraph 1 and all the number listings of the fonts don't need any commas, so just Source Sans Pro Light 300 for both Merriweather and Source Sans Pro.

**Comment by carodew** [comment]
Can this issue be closed? @maya @angel

**Comment by maya** [comment]
Yup, closing now.
