### ISSUE TITLE
[Links] New tab link missing external link icon

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#575]
Missing this icon (http://fortawesome.github.io/Font-Awesome/icon/external-link/) to the right of new tab.

**Comment by carodew** [comment]
<img width="925" alt="screen shot 2015-09-16 at 4 52 42 pm" src="https://cloud.githubusercontent.com/assets/10144074/9918178/634be008-5c93-11e5-864f-d98cb0b84f67.png">

**Comment by maya** [comment]
This never made it into development.

**Comment by carodew** [comment]
The issue is that there is a WH initiative that links leaving .gov sites are required to warn you that you are leaving a government controlled site.

On the other hand, many agencies don't think this icon is enough to fulfill that requirement. 

Also, if this is why this is a high, the text needs to be different. But not before launch.

**Comment by maryjom** [comment]
In addition, the code doesn't match the .pdf of the components_sticker_sheet_and_read_me_V.8 which shows the icon on the external link.

**Comment by danamuses** [comment]
I would love to see guidance here about how to indicate exit links. For example, on Archives.gov we use an arrow icon which provides disclaimer language in the hover state or links to a full disclaimer page on our website.
