### ISSUE TITLE
[Search bar] clicking on 'search' reloads 'Search bar' page in Safari

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#595]
*To recreate*
On 'search bar' page, click on any of the 'search' buttons. Page will reload. 

http://screencast-o-matic.com/watch/coQDFpfKVc

*Expected behavior*
No action should result from clicking on example search button. 

*Tested on*
OS 10.8
Safari 6.2

**Comment by carodew** [comment]
Bug triage thoughts: 

*it's because there is a submit button that is trying to submit something
*short term solution would be to not make it a submit button, but that would make the code not relevant for people who download it
*long term solution might be to create a JS solution that would prevent the button from reloading the page

**Comment by joshbruce** [comment]
Could disable the button as well - this would require adding a styleguide class to give the proper button color, but would make it so the page doesn't reload. Could also use JS prevent default.
