### ISSUE TITLE
[Buttons] Code on buttons page is cut off on iphone safari

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/web-design-standards#598]
*To recreate*
On 'buttons' page, click on 'Code' tab.  The text is cut off on iphone safari.  

![img_7566](https://cloud.githubusercontent.com/assets/3680494/9918620/dfaab2c6-5c95-11e5-9dd2-4981cb6f139c.PNG)

*Expected behavior*
All code text should be present/visible on page.  

Tested on
iPhone 5
Safari

**Comment by NatalieEMoore** [comment]
won't let me upload picture currently

**Comment by carodew** [comment]
@NatalieEMoore I believe this is expected behavior as we don't want the code wrapping excessively. It is possible to scroll horizontally to see the full line width – possibly we should also have a horizontal scroll bar visible if it's too easy to miss. I'll add that to our list of research questions to address after the MVP. 

Thanks!
