### ISSUE TITLE
[Typography] Page performance has extra space and wrong label

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#633]
On Chrome when I go to the pairings and fonts and then click into a pairing to see the page performance section I see this: 
![image](https://cloud.githubusercontent.com/assets/103496/9953166/2599dade-5d93-11e5-9810-90633de5418f.png)

![image](https://cloud.githubusercontent.com/assets/103496/9953153/0b51a09e-5d93-11e5-9868-11c682c39428.png)

1. The page performance header should top-align with the paragraph on the right. 
2. The high and medium labels of the pairings should be switched. 
3. The labels should have colors associated with high and medium. Can we make high be the secondary color with white text and the medium to be gold with base text?

**Comment by jpyuda** [comment]
I'd rename the labels to be less confusing (what does "high" mean anyway?) as per @maya's suggestion.

I think we should hold off on colors until we can extend the label component to support that more broadly.

The spacing above the sidebars is a "low" IMO.

**Comment by carodew** [comment]
@colinpmacarthur will change to "Fast" and "Medium" for clarification. 

We think we can ship without the color change and the spacing.

**Comment by colinpmacarthur** [comment]
In response to @angel's three points in the issue description:

> The page performance header should top-align with the paragraph on the right.

We decided this was a separate low priority issue at bug triage. Opened #648 in response.

> The high and medium labels of the pairings should be switched.

Although the wordings on the page were from the original copy, everyone agreed they were confusing. #647 changes the labels of "high" performance font pairings to "fast."

> The labels should have colors associated with high and medium. Can we make high be the secondary color with white text and the medium to be gold with base text? 

We agreed at triage that this was an enhancement because we currently don't offer colored labels in the library. Opened #649 with that enhancement suggestion.

Thanks @angel!
