### ISSUE TITLE
Feature Request: Prohibit the use of carousels, backed with reasons. Showcase best practices for alternatives to carousels

### ISSUE THREAD

**Issue by jjoteal** [18F/web-design-standards#64]

**Comment by carodew** [comment]
:) I think this is our first anti-feature request.

**Comment by ErieMeyer** [comment]
+ 4857349587345097!!!

**Comment by Scotchester** [comment]
:+1:

**Comment by mollieru** [comment]
Love it!!

**Comment by meiqimichelle** [comment]
+1

**Comment by colinpmacarthur** [comment]
If we decide to discourage carousels, let's give some good reasons and cite the relevant research (like http://www.nngroup.com/articles/designing-effective-carousels/). Even better, let's suggest some good alternatives.

**Comment by AccessForAll** [comment]
+1

More anti-carousel references:
* WebAIM, featuring an accessibility point of view: Should I Use a Carousel? – http://shouldiuseacarousel.com (background info on the "Should I Use..." site: http://www.creativebloq.com/accessibility-expert-warns-stop-using-carousels-7133778)

* Search Engine Land (with suggestions for alternatives): Homepage Sliders: Bad for SEO, Bad for Usability – http://searchengineland.com/homepage-sliders-are-bad-for-seo-usability-163496

**Comment by carodew** [comment]
Moving this into our workflow, thanks for all the comments!

**Comment by mebates** [comment]
Did this make it into the standards?

**Comment by carodew** [comment]
Hi @mebates – we've got a road mapping meeting next week and we're going to talk about what we want to build in the next six months / year. I know it's been awhile, but the new team is working again and we should start seeing more progress soon. 

I personally am going to advocate that we provide guidance against anti-patterns and alternatives, because I think this is a good idea. If you want to add fuel to that fire, please feel free to add arguments here. :)

**Comment by carodew** [comment]
Also – gov timelines – AMIRITE?

**Comment by maya** [comment]
We'll consider adding this to the Standards if we create a larger "dark patterns" section or as part of the documentation for another component, like a static hero element. Closing for now, but thanks for your support on this issue!
