### ISSUE TITLE
z-index: -1 on .main-content and .sidenav makes page unworkable

### ISSUE THREAD

**Issue by robertsosinski** [18F/web-design-standards#654]
In `styleguide.css`, the following two selectors set `z-index: -1`:

```
.sidenav {
  position: fixed;
  ...
  display: none;
  z-index: -1;
}

.main-content {
  position: absolute;
  ..
  padding-top: 1em;
  z-index: -1;
}
```

By doing this, when using Chrome, it seems that elements on the page are not workable (clickable, selectable, focusable, hoverable, etc...).  I've commented out the `z-index` value on `styleguide.css` and everythign works just fine afterwards.

**Comment by mollieru** [comment]
@robertsosinski we think this is because you're using the styleguide.css file for the Web Design Standards site itself in your own site. 

If you use main.css this will give you everything you need, instead of needing styleguide.css 

Can you tell us how you got yourself to styleguide.css? 

Here's the general directions around this: https://pages-staging.18f.gov/web-design-standards/getting-started/

**Comment by maya** [comment]
Hope this answered your question. Let us know if this still seems to be a problem.
