### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by robertmain** [18F/web-design-standards#745]
It would be really nice to have a `bower.json` file in this repo. That way, people could just add it to their bower file removing the need to clone the entire repo.

**Comment by matyasfodor** [comment]
:+1:

**Comment by mollieru** [comment]
Thanks for the input! We've been discussing adding this as well. We'll keep you posted!

**Comment by Scotchester** [comment]
:+1:

**Comment by kiblerdude** [comment]
:+1:

**Comment by andrewliebchen** [comment]
NPM too.

**Comment by robertmain** [comment]
npm isn't really for client side dependencies though

**Comment by andrewliebchen** [comment]
It is though. React and React components are distributed on npm. So is Bourbon, which is a dependency if this library. It's not tough to publish to both bower and npm.

**Comment by matthewjewell** [comment]
:+1:

**Comment by jeremiak** [comment]
Hi all, love the feedback! I like where this is going and completely agree that we should make the design standards a bit easier to leverage in your projects through dependency management tools (i.e. `bower` or `npm`). However, 18F projects don't use bower as a matter of policy (18F's front end policies and guidance can be found in our [Front end guide](https://pages.18f.gov/frontend/recommendations/dependency-management/)).

I'm going to close this issue, as I did wth #760, in favor of #767 (making the standards available through `npm`) because it strives for the same goal of making it easier to include the design standards in your project and get started using them.
