### ISSUE TITLE
Consistency of input types, dates should be a single field

### ISSUE THREAD

**Issue by IDisposable** [18F/web-design-standards#751]
Giving this;
> Avoid breaking numbers with distinct sections (such as phone numbers, Social Security Numbers, or credit card numbers) into separate input fields.

I have to strongly disagree with this:
> Three text fields are the easiest way for users to enter most dates.

Please change this to a more reasonable single input field.

**Comment by jcbelanger** [comment]
I also strongly agree.  You should always avoid trying to be clever and use a single, traditional input.  My reasons are:

* A field broken into sections also requires proper aria markup to ensure each section is properly handled readers.
* How form errors be represented to a screen reader when the input is split into sections?
* This prevents the user from selecting the entire input (to copy/paste or clear contents).
* A user should be able to input for a field without having to hit tab / use the mouse.  The extra steps are not conventional and can cause issues for users with cognitive/motor disabilities!
  * A field broken into sections often includes scripting to manage field focus / cursor placement.  This will not work without JavaScript enabled.
  * Even changing the user focus pragmatically can be distracting and can cause issues for people with cognitive disabilities if it isn't exactly as they expect / used to.
  * If focus goes forward to the next section automatically, it should go backwards automatically with backspace.  This means supporting ALL of the platforms cursor keyboard shortcut conventions: shift+left/right=select text, ctrl+left=move cursor a word in reverse, ctrl+shift+left = move cursor and select a word in reverse, home/end/etc...  This all has to work across potentially multiple sections!  Any mix can cause issues for users with cognitive/motor disabilities!

**Comment by AdamDavis321** [comment]
I also agree. In addition to the points made by IDisposable and jcbelanger, I think using a single input field would allow for more consistency with HTML 5 date input fields and the date input components provided by most JavaScript frameworks. In my opinion, users will not be surprised by single-input fields for date entry, and they will be seeing that paradigm more and more in the future.

**Comment by carodew** [comment]
Thanks for the feedback, we put this alpha version out for this exact purpose! We can definitely see how our overall recommendations might be contradictory and we’ll want to resolve that. 

In the long run we’d like to offer a few different variations on date inputs and recommendations on what contexts they would be appropriate for (feel free to search our issues for ‘date picker’ and ‘date input’) 

Our reasons for recommending three fields were specifically because: 

* Javascript-based input masking to add formatting (which we’d want for a single-date input on older browsers) can lead to bad accessibility problems (See a demonstration here: https://docs.google.com/a/gsa.gov/file/d/0B9rGmqNcHo-mRGpMS0xQbzVzeGM/edit). We’ve partially solved this in other areas by using PoliteSpace by Filament Group (https://github.com/filamentgroup/politespace) but in our testing we found that sighted users expected the formatting to appear both when the field has focus and when they click away.

* We wanted to visually separate each element of the date to make it easier to validate. For example, it’s easier to validate three inputs rather than one: if someone types 11315 do they mean 11/3/15 or 1/13/15? 

*  The UK’s Government Digital Service has found success using three separate fields. They visually separate the elements of the date and avoid using Javascript-based masking techniques. (See https://designnotes.blog.gov.uk/2013/12/05/asking-for-a-date-of-birth/) 

We actually recommend against using JavaScript to automatically move focus to the next field in any form.

That being said, we’re open to hearing arguments on why this might not be the best choice. Given what we’ve mentioned above, do you still think that one input field is better? Are there other solutions we might consider? 

Thanks!

**Comment by jcbelanger** [comment]
While I'm glad we both agree moving user focus is bad, I brought it up because I thought it highlights a tendency UX designers have to change go against platform conventions which can cause a worse UX in other cases.  This is why I'd also be hesitant to use something like PoliteSpace that you linked.  (I love most of the work by the Filament Group too!)  An input field represents what the user entered.  If it's not EXACTLY what the user typed, it can cause some confusion.  Pretty, formatted, styled content belongs in a new element.  <input> elements are for raw input and should not be overloaded.  This is why I suspect your users were confused to find the difference between the editing and display of their input.

While a single input might not be as pretty, it's SIMPLE and avoids all of the subtle issues that arise with splitting inputs.  I don't find the 3 reasons listed for splitting inputs as strong because it seems each reason is similarly misguided as moving user focus.

* Masking. I believe the browser's convention is to use placeholders instead.  It's nice that when you split an input, you save the user from having to input formatting characters, like the '/' in '1/1/2015'.  But this is at the cost of the user having to hit tab (and hoping no script messes with the focus) or use a mouse, which is really bad for users with motor disabilities.  And even then, you'll still need placeholders for each section.

* Validation.  If someone types "11315", you should report it as a formatting error!  People are always trying to interpret a user's intentions and constantly getting it wrong.  I believe it's better to give the user feedback in the form of an error instead of potentially interpreting their input incorrectly.

* Visual.  I completely agree that 3 inputs can look visually better than one.  This neglects non-sighted users who will rely on the placeholder (as fallback) to gather context about the field.  Marking the "MM" field as invalid is not very helpful to the user!  This raises the issue of how to represent an error over the entire input.  If your business logic limits your dates to a range, will a screen reader say 3 fields are invalid for each invalid date?

Here's one more issue I just thought of: I also don't think splitting inputs works well for optional field components.  For example, the Country Code / Area Code components of a telephone number might be optional depending on the use case, but a split telephone number would be much more verbose to the user.

**Comment by migurski** [comment]
Yikes—anyone here have any research results from putting this in front of users to support a change? GDS [formally recommends split fields for “memorable dates,”](https://www.gov.uk/service-manual/user-centred-design/resources/patterns/dates.html) distinct from other kinds of dates.

The USDS playbook is down right now (“MAX.gov is scheduled for maintenance on Sundays 2:00am-8:00am EST”) and I don’t recall if USDS similarly distinguishes a variety of date types.

**Comment by maya** [comment]
@migurski GDS states: "We’re currently recommending using three fields as it’s easier to reliably validate than a single field."

**Comment by migurski** [comment]
Yep, that’s the one for memorable dates. The recommendations are substantially different for other kinds of dates, e.g. “If you don’t need an exact date and users are likely to struggle to remember it (for example the date you started your first job), make sure you allow users to enter approximate dates like ‘June 1996’” which would imply a single input for that kind of date.

Kind of a pain that the standards are down every weekend. Are the servers powered by union hamsters?

**Comment by maya** [comment]
@migurski Right, we're just addressing [memorable dates](https://pages.18f.gov/designstandards/form-controls/#date-input) on the standards. 

Also, https://pages.18f.gov/designstandards/ works. It's the proxy that's handled by OMB giving us issues. Our servers are fine.

**Comment by migurski** [comment]
:+1: :100:

**Comment by joelanman** [comment]
Hullo - I worked on the GDS guidelines.

When you give users a single input box for date, it's more ambiguous what date format you want from them. We've tested it and regularly seen people pause and wonder what format they should use, and be unsure that what they enter will be accepted.

When your input pattern is more defined (as with using three boxes) you don't have that problem.

As with everything, we'd recommend people test the pattern in your context with your users.

**Comment by maya** [comment]
That is a great answer @joelanman, thank you! I think context is everything, and you should test for your specific use cases.

**Comment by mpeter88** [comment]
Two comments:

1. To the last response from joelanman: Due to the the possible formats of date representation, date input fields typically need a format hint such as "MM/DD/YYYY", and as such a single box is no different from three boxes. You all use "Month", "Day", "Year" plus an example so that the user knows it's 2-digit month and day, and 4-digit year. Users need that hint in case the first box was, e.g., DD (Europe) vs. MM (USA). As such there is no inherent clarity in using three boxes vs. a single box. So it seems to be a stylistic choice, which is fine.

2. Input validation: Text entry requires validation on both the client and server side to make sure that valid input was received. Using drop downs (or spinners in terms of mobile devices) is easier in that regard, as it constraints input to an enumerated value on both the client and server side, reducing the validation burden and possibility of an introduced error. It also offers some UX optimization due to allowing either drop-and-click vs. fingers-on-keyboard, or shortcut entry, e.g., where "F" or "2" brings up "February". From an engineering perspective, this is the best practice.

**Comment by maya** [comment]
Adding this note I received from Tom Byers of GDS:

To add to that, it does depend on the people using your form and how reliably you can validate the input. Our [CMA cases page](https://www.gov.uk/cma-cases), for example, uses a single field because it has specialist users & is part of a Rails app. Because the types of users it has are more consistent than other services the team was able to check the date formats used by them and make sure to support them. Rails also has much better date libraries than other tech so this wasn't too much work to do.

I worked on the https://www.gov.uk/register-to-vote service which uses a split field. This service had to work for everyone in the UK so the user-base was much more varied. Under these circumstances it was a lot less clear the things people would end up entering.

Research sessions for register to vote showed users found the supporting text, including validation messaging, and labels for the field are crucial in guiding their use of the field. This informed how we organised the work, in other words, with less data on what would be entered we focused on making the questions we asked as clear as possible.

I can't point you directly at specific research but our teams use a Hackpad to share their research and discuss patterns. Here's the one for dates: https://designpatterns.hackpad.com/Dates-vpx6XlVjIbE. The one thing I'd point to in that is the research Alice did on the patterns her users were entering (mentioned above). This work was key to understanding the impact of enforcing a single-field approach and I'd recommend you do this kind of thing as much as possible.

**Comment by carodew** [comment]
I'm reopening this issue since there is still a lot of conversation happening, and I want to be sure feedback is captured (and stays in one place, as much as possible). 

Thanks everyone for your thoughts! Ultimately this is just our first iteration (and alpha)  and we will consider this feedback as we further test and refine this pattern. 

Here are a few of our reasons for starting with this particular pattern: 

Hints within text inputs (placeholder text) can have a lot of accessibility issues, and are easy to abuse. Some of the trickier aspects include:  

* The gray text that appears usually does not meet 508 contrast requirements, making it difficult to read for people with sight issues. 

* Making the text darker to meet these contrast requirements can lead to sighted users scanning the form to think that the form fields are already filled out. Hence, we're not using placeholder text and instead ask that instructions and hints be included within the `label` element to remain accessible to screen readers.

* Placeholder text disappears as soon as the field has focus, meaning people using keyboards have to read ahead to catch anything useful the text provides. This also presents issues for people with memory problems. 

All that considered, that doesn't mean that placeholder text can't be used, but we wanted to start out our recommendations with the safest possible default. As Tom Byers mentioned above, it ultimately depends on your audience and context, so be sure to do your own user research.  

We do want to add input validation and that will be coming in a future release.
