### ISSUE TITLE
Name form template does not support mononyms

### ISSUE THREAD

**Issue by natdudley** [18F/web-design-standards#753]
## Description

The form template for names has two mandatory name fields and does not support mononyms. As such, can be exclusionary towards people of Javanese, Turkish, and Icelandic origin, amongst others. Not everyone has two names.
## Ask

Please amend the form template https://playbook.cio.gov/designstandards/form-templates/#name-form to recommend a single mandatory name field.
## To Do
- Remove mandatory status on Last Name field.

![screen shot 2015-09-30 at 7 35 41 am](https://cloud.githubusercontent.com/assets/3861245/10174350/e00e48e4-6745-11e5-9faf-0faa7f46a386.png)

**Comment by carodew** [comment]
Thanks @natdudley! That's a good point. We're going to look into this more closely.

**Comment by donjo** [comment]
Closing this issue since the name form template is just an example and at the end of the day developers using the standards will have to adjust the fields they are asking for based on the data store their form is connecting to. In the guidance section of the name form template we now provide the following guidance to let folks know that there are exceptions to the rule:

```
## When to consider something else
If you don’t need to parse out the separate pieces of a person’s name, consider letting them enter it into a single text field.
```
