### ISSUE TITLE
Make NPM installable. 

### ISSUE THREAD

**Issue by hasimpson-usgs** [18F/web-design-standards#767]

**Comment by jeremiak** [comment]
**Some background**: It is pretty clear from #745 and #760 that folks want to be able to easily use the design standards with the dependency management tools already in their toolchain. The 18F front end guild provides guidance around dependency management through the [respective guide](https://pages.18f.gov/frontend/recommendations/dependency-management/), which advises the use of `npm` instead of tools like `bower.

**Comment by andrewliebchen** [comment]
You could probably combine this issue with [this](https://github.com/18F/web-design-standards/issues/403). That way, you'll set up npm to handle your dependencies and publish at the same time.

**Comment by openbrian** [comment]
Hey all, i was teaching myself about NPM packaging today, and i thought i'd use my teams project from the recent #GSAhackathon as a test subject.  We wanted to use the WDS in our sails and sass based project.  Being new to this, i'm not sure i did this in a reasonable way.  I followed a pattern based on node-bourbon and node-neat.  It uses node-sass so it's all ruby based.  Check it out, use what you can.  https://github.com/openbrian/18f-contrib-web-design-standards  Any feedback is appreciated.

**Comment by jeremiak** [comment]
Hey @openbrian that looks pretty cool, nice work. I followed a pretty similar pattern in #902

**Comment by maya** [comment]
The package is published and can be found here: https://www.npmjs.com/package/uswds
