### ISSUE TITLE
Questions: overall implementation and adoption

### ISSUE THREAD

**Issue by hlfcoding** [18F/web-design-standards#781]
First off, what's here looks amazing.

First question is did you consider using Bootstrap instead of specifying what seems to amount to a custom frontend framework using Bourbon and Neat? I'd imagine Bootstrap having much more adoption and being much better maintained than most other frontend tools out there, while covering more edge cases than what I see in the current standards.

Second question is have you considered how some standards affect long-term adoption? I'm imagine some of the more opinionated requirements like the 12-column grid aren't very future-friendly, especially when there's nothing about responsive layouts.

I wouldn't call either of the above issues, but more like vague concerns.

**Comment by maya** [comment]
Thanks for the question and kind words!

There are enough articles out there that describe why someone may not want to use Bootstrap. In fact, we take it for granted that Bootstrap is the assumed thing to use. 

Bootstrap was built as an internal tool for employees at Twitter. Our system was built for designers and developers in federal government - with our own set of needs, requirements, and preferences. Our system was informed by speaking and testing with designers and developers throughout govt.

Here are a few considerations:
- We get to follow our own conventions and coding style of the [18F frontend guild](https://pages.18f.gov/frontend/)
- We built it from the ground up the way we commonly start our projects for the federal govt
- We're building in accessibility from the start as a core competency
- We would have to undo a lot of Twitter’s CSS, so this is not very maintainable. Our system was built just for us.
- We're thinking about modularity and reusability of our components in a holistic way
- We built this to be lightweight, flexible, and modular
- We’ll be able to grow and extend our system as we test it out and learn from real-world projects

For your second question, we rather like using Neat's grid, and tend to start most projects with it (which need a grid), so it doesn't present any problem for us. We think the folks at thoughtbot do a pretty good job with support too and support open source projects. Our CSS is built mobile-first, outlined in the getting started section, so it's responsive from the get-go. But yes, any UI framework will have opinions and conventions, these are just ours ;)

**Comment by csakis** [comment]
I welcome bourbon and neat. I think they are very interesting and modern techniques, I have never used them myself but am looking forward to learn them. By choosing them you made your job much harder convincing others to comply with this new standard.

**Comment by carodew** [comment]
We did discovery research early on with developers working within several federal agencies and learned that they: 
*prefer to pick and choose the components they need and only download the bare minimum code necessary, which they reported was difficult to do in Bootstrap
*felt that Bootstrap was too class-heavy and opinionated
*reported that Bootstrap was difficult to customize and tweak
*often had to spend many hours reverse engineering Bootstrap components in order to make them accessibly and 508-compliant, a requirement for government websites.

**Comment by kottenator** [comment]
BTW, you use Neat which documentation says:

> We built Neat with the aim of promoting clean and semantic markup

This means that Neat wants to avoid `.another-grid > .col-3`. But you bring `.usa-grid > .usa-width-one-third` which breaks semantic markup...

I understand that it's necessary in order to use plain CSS instead of SCSS... 

So I come to a general question: do you strictly recommend to use plain CSS? Or do you also recommend to use SCSS with "pure" Neat and Bourbon?
