### ISSUE TITLE
Discussion: sustaining design consistency

### ISSUE THREAD

**Issue by WestonThayer** [18F/web-design-standards#813]
...following up from [twitter](https://twitter.com/18F/status/652111938353295361?cn=cmVwbHk%3D&refsrc=email).

The [U.S. Web Design Standards](https://playbook.cio.gov/designstandards/) is an awesome and noble effort that touches so many Americans. It attempts to solve the problem of design consistency at a scale rivaling or surpassing major design studios like Google or Microsoft. Design consistency seems to be a nearly universal issue in our field (heck there's practically a [whole site](http://styleguides.io/) dedicated to it), so I'm hoping that this discussion will benefit everyone.

Achieving design consistency can be broken into two main areas:

* **Initial effort** - agreeing on standard guidelines and components, then implementing them consistently across many endpoints
* **Maintenance effort** - as time passes, constraints change and components occasionally must adapt to ensure continued success

While both of these come with their own challenges, I'm primarily interested in talking about the technical details of the second. The U.S. Web Design Standards take a Boostrap-eque approach to component distribution. Styles are consolidated and abstracted, but the HTML architecture of components (a.k.a. `<div>` soup) must be copy/pasted into each endpoint. An alternative approach that abstracts *both* style and HTML architecture can be found in the [Web Components](http://webcomponents.org/) spec, or libraries like [React](https://facebook.github.io/react/), [Angular](https://material.angularjs.org/0.11.2/#/), or the many others created by the JavaScript community

There are pros and cons to either approach that have large impacts on a design team's ability to maintain consistency. How did everyone at 18F go about choosing their approach? What advantages do you see to the Boostrap-ish path? What are you worried about in the future?

**Comment by rwfeather** [comment]
I agree that the technical details of the specification may benefit from a more component-esque approach. The Bootstrap approach works in a lot of UI framework cases where you don't mind the individual designers having more freedom. Bootstrap and frameworks like it simply provide the styles which in turn provide the "components". 

For an example of a component-first approach, take a look at [Elemental UI](http://elemental-ui.com/). Where the relevant html, styles, and scripting are encapsulated in the React component and customization happens through verifiable properties. This may more closely align with the goal of **standardization** rather than providing a framework.

**Comment by WestonThayer** [comment]
I totally agree, we need standards, not a you-must-work-this-way framework. I think that's one of the big downsides to Angular or Ember components. React or Web Components + polyfills seemed like the two strongest candidates when I was researching. Elemental looks like its off to a great start. My money is on style guides taking this approach eventually.

The downside to both of these approaches is the bar to entry. It's easy to reference some CSS files and paste some <divs> into your HTML. It's asking a lot more to figure out how to incorporate a component library. I'm interested in ways to lower that barrier. If you guys end up going this route in the future, let's talk.

**Comment by msecret** [comment]
Hi @WestonThayer, I'm one of the front end developers who worked on the standards.

There's a couple of reasons we've chosen the approach we did. I think the bar to entry is a major reason for choosing this method. Our initial research highlighted that many of our potential users in government were more comfortable and would be better served by a simple copy and paste method of applying the standards. Many of the people we interviewed didn't have the workflow setup to easily implement something like React or Angular. The fact that React, and likely Angular, requires a build process would alienate some of our potential users. In terms of web components, we found that people were more comfortable coding HTML and CSS and staying out of the Javascript land.

Another aspect of this, which is still being debated within our group at 18F, is accessibility when Javascript is disabled. Many of the projects we've worked on at 18F have requirements that the page is at least readable and presentable when Javascript is turned off. This requirement makes it harder to go with the web components route (I've never actually seen a widely supported method of rending web components without javacript) and would make the React and Angular routes even more complicated (having to do server-sided rendering). We at 18F eventually want to research and come to a formalized conclusion on whether we should build sites that won't work without Javascript, but until we do that, we have to accept it as a requirement for at least some of our sites.

I should also mention that maintainability is something we considered while build our library in this way. It's been our goal to make the style of our components separated from the markup. This means trying to stay away from styling specific HTML elements and using classes instead. Our hope here would be that we could change the styling of the standards without having to change the markup at all. That being said, we did find it difficult to fully support this idea, so we have some additional work and research to do in order to be successful with this.

**Comment by WestonThayer** [comment]
@msecret Thank you, that's exactly the insight that I was looking for. Excellent call with the accessibility piece, I hadn't thought of that. It'll be interesting to look back in a few years and see how much markup ends up needing to be changed. Hopefully not much :)

**Comment by buckaroogeek** [comment]
We are in the process of evaluating some additional tooling around our web
and web application standards so that we can continue to support multiple
technical stacks that are present in our agency. The public facing web is
built on Drupal or a Java Portlet standard (headed towards retirement) as
well a number of static pages served up by plain old apache. On the web
application side of our agency there are applications based on JBoss,
Oracle Weblogic, Websphere, IIS, PHP, and so on.

My thinking is that tooling that includes a build process (eg gulp) and a
dependency manager (npm perhaps) and possibly yeoman could help us
immensely in publishing standard versions of our agencies template that
will work well in these different stacks. Having components as a foundation
and standard published versions generated by the built process seems to be
doable.

Something that is definitely a work in progress at the moment.

Brad

**Comment by carodew** [comment]
@msecret Great points! I agree on all the framework decisions. I just want to clarify a few things that came up in the user research:

We found that developers, when asked to consider whether they would use a specific component in their project, went through three primary steps: 

1. **Kick the tires of the component.** In this phase they would play with the component itself and see if it behaved in the way they desired or expected. 

2. **Examine the code.** After playing with the component, developers would look at the code and look for things like, "is this HTML clean and semantic? Does the CSS make sense to me? What can I modify here and not break the component?" This is why we needed to display at least the HTML on the page itself. They wanted to do this process before committing to downloading something. I think in future iterations we should explore also showing some of the SCSS and possibly JavaScript, but I'm listing those in decreasing importance, and more research needs to be done in this area. 

3. **Download the code.** The last phase is downloading the code, and we actually found that instead of copy/paste, having a download package for the entire component was the easiest. When we make users copy/paste the HTML and then link up the CSS and JS files, all sorts of problems and difficulties come up. The files aren't linked correctly (they aren't linked at all), they didn't have the entire line of CSS or JS that they needed, etc., or they would have to add in the HTML header and footer accoutrements to make everything work correctly.  Some users want to download everything in a package, but most users also expressed a desire to pick and choose what components they wanted to use, and didn't want to be forced to download something in it's entirety (adding a lot of extra weight to their code). 

The question came down to feasibility within the MVP and what was the minimum we needed to include prove the concept. There were a lot of questions we had yet to resolve, including, what do you do if someone downloads the header and footer separately, both of which rely upon the same CSS styles? Does the user download duplicate files in that case? What if a user downloads a footer and accordion separately, while the accordion is actually contained in the footer? Do you have to download both? Does the footer break if you don't download the components it contains? 

As we move forward into the next phase I think we can address a lot of these questions through more research and iteration, and provide more options for downloading the code. Build, measure, learn. :) 

cc-ing @colinpmacarthur on this response in case he has anything to add.

**Comment by colinpmacarthur** [comment]
Agreed with @carodew.

I'll just reiterate that, although developers wanted Bootstrap-style HTML snippets on the standards site, they also expressed interest in some kind of downloadable  "packaged" version of the components. We didn't include that in this alpha, but I'd certainly argue for it in the future.

**Comment by mollieru** [comment]
Really great discussion everyone.  @WestonThayer did you get your big questions answered? 

// sidenote: this would make great foder for the technical-focused blog post on development decisions of the standards. @maya @msecret you guys might want to hang on to notes from this discussion as you draft this!

**Comment by WestonThayer** [comment]
Definitely, thank you. I agree, this would make an excellent blog post :)

**Comment by maya** [comment]
@WestonThayer absolutely, and I find number 2 "Maintenance effort" the most interesting part. Even within a single org, I bet we'll find a lot of variants in how the standards are used. We tried to build flexibility in from the start so that it would get adopted. This means we'd sacrifice some consistency but I think that's ok bc we want this to be accessible to the greatest number of people.

A few things I think will help:
- Trying not to change the HTML markup bc we're building on a solid HTML core
- Keeping a detailed [change log](https://github.com/18F/web-design-standards/pull/779) for people to follow along
- Version control and dependency management via npm
- Creating a rich community where we can talk about these exact things, like here

We'll be able to learn more after further research and testing.
