### ISSUE TITLE
Draft VA footer variation 

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#855]
The VA digital service team has been working up a slight variation on the standards' suggested footer layout. They asked for some feedback. 

@carodew @angel @colinpmacarthur (and anyone else) would love your thoughts!

![va_draftfooter](https://cloud.githubusercontent.com/assets/3680494/10673276/f1a28370-78c2-11e5-9f21-7833bfa16d70.png)

// cc @emilyville @raineystraus

**Comment by carodew** [comment]
Is there a prototype we could click around/play with? Hard to really examine it with just a screenshot. :)

**Comment by mollieru** [comment]
@emilyville @raineystraus ^^ do you gals have a prototype for us to play w?

**Comment by emilyville** [comment]
@carodew Here's a URL to see something close
http://department-of-veterans-affairs.github.io/beta-site/

Note that this is in foundation. I'm building one for the GI Bill tool now that is using web design standards. I'll send that one when it's up somewhere shareable!

cc/ @rickleegit

**Comment by rickleegit** [comment]
I believe that the link styles are also preparing to be altered.

**Comment by carodew** [comment]
Noice!

I'm really, really, really excited to see this. Also, might you or one of your team mates be interested in participating in a usability interview about your experience using the web design standards? 

I think the content is well organized and I like the horizontal strips of information. If I were a UX-er on this project, I'd probably have the following research questions that I'd want to test with my users: 

1. Do people think the category headers (Benefits, Resources, Process, Connect) in the footer links are clickable? Do they confuse these with links or are they visually distinct enough that it's clear? 
2. What do users think the category Process means? What do they think the Playbook is? What is the difference between a Benefit and a Resource?
3. I notice the speech-bubble/lightbulb icon in the lower right is fixed to the viewport, while the rest of the content scrolls with the rest of the site. Do users understand what that does or what that's for when it's not paired with the explanatory text? Is it a priority for users or should it be fixed with the rest of the footer? 

Visually I'd like to see the spacing around the Crisis Line refined a bit but that may already be part of the plan. I think it stands out nicely given the color contrast. I'd be curious to know the emotional state of someone calling the crisis hotline and how that affects how they use the site.

**Comment by rickleegit** [comment]
Always happy to participate in UX interviews conversations!!!

Following launch, that is. :-)

**Comment by colinpmacarthur** [comment]
Nice work!

I agree with @carodew's comments. 

A few other questions pop to mind: 
1. Any thoughts on having both "vets.gov" at the top of the footer as well as "Department of Veterans Affairs" at the bottom?
2. Any thoughts on the capital VA in addition to the VA seal? Trying to include both a logo?
3. Would love to hear more about why the crisis line and contact us / social media icons are in different places?

None of these are meant as criticisms - just trying to understand the design constraints so we can make the standards' footer better. :)
