### ISSUE TITLE
Zip file names do not match

### ISSUE THREAD

**Issue by rtwell** [18F/web-design-standards#932]
When a user downloads the file wds-design-**v0.8.2**.zip, it unzips to a folder named wds-design-**v0.8.1**, which is confusing. The naming conventions should match.

**Comment by jenniferthibault** [comment]
@rtwell : I just tried this out, and noticed that it actually unzips **v0.8.2.zip** to a folder called **assets**

If you have your finder window sorted by date, they'll appear next to each other in order, and see this:

![screen shot 2015-12-18 at 12 27 22 pm](https://cloud.githubusercontent.com/assets/11636908/11902838/b9e10546-a582-11e5-8fa1-1fe89216e760.png)


 If you have your finder organized alphabetically (which is my default) "Assets" sort of :ghost: s to the top. So if you downloaded the first set of assets at one point, and it's still hanging out in your downloads folder (which it is for both of us, so seems not uncommon) it LOOKS like the file you just opened is wds-design-v0.8.1

![screen shot 2015-12-18 at 12 28 06 pm](https://cloud.githubusercontent.com/assets/11636908/11902876/e9410476-a582-11e5-9466-227d19ed7326.png)


I agree with @rtwell and suggest that the unzipped folder should have, or start with, the same name as the zipped file (v0.8.2.), so that this sorting conflict is no longer a risk.

**Comment by rtwell** [comment]
Here's what i get when I unzip the contents of v0.8.2.zip:
![screen shot 2015-12-18 at 11 37 35 am](https://cloud.githubusercontent.com/assets/12564977/11903033/dabc9c8c-a57b-11e5-9349-1f44dae383f0.png)

No assets folder to be found.

**Comment by jenniferthibault** [comment]
Ohhhh - you were downloading just the design assets, I was downloading the whole components (from the front page). I think this means it could be a two-part improvement 

So from your findings, `wds-design-v0.8.1` should be renamed `wds-design-v0.8.2`
From what I found, `assets` (which is the whole shebang of code and components) should be renamed `wds-v0.8.2`

**Comment by maya** [comment]
@rtwell The issue with file naming has already been resolved in: https://github.com/18F/web-design-standards/pull/912 and will be available in our next release.

**Comment by jenniferthibault** [comment]
@maya from the comments, I can't tell if #912 addresses the `assets` naming inconsistency as well or not. Is that something you are also thinking about changing?

**Comment by maya** [comment]
@jenniferthibault I think we're keep the code named `assets` so people can drop the whole file into their source code. I think we'll end up adding something else to that file for it's version number, like a change log.
